name: Github Actions Demo
on: [push, pull_request]
env:
  myTime: date
jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        run: echo "Event that triggered the job:${{github.event_name}}"
      - name: Set Time
        run: echo "myTime=$(date)"
      - name: Output Time
        run: echo "Time was $myTime"
      
      
